[package]
name = "nadi"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["highlighter", "markdown", "lazy", "tokio", "svg"] }
nadi_core = { version = "0.6.0", features = ["functions"] }

tokio = {version = "1.44.1", features = ["fs"]}
rfd = "0.13"
